# Generated by Django 4.0.5 on 2022-08-17 02:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_course_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('slug', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to='Course.course')),
            ],
        ),
    ]
