# Generated by Django 4.0.5 on 2022-08-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_coursecategory_remove_course_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptervideo',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
