# Generated by Django 3.2.4 on 2021-12-12 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('slug', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('user_type', models.CharField(choices=[('Student', 'Student'), ('Tutor', 'Tutor')], default='Student', max_length=20)),
                ('mobile', models.CharField(blank=True, default='', max_length=22, null=True)),
                ('area', models.CharField(default='', max_length=500)),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=10)),
                ('detail', models.TextField(default='')),
                ('qualification', models.CharField(default='', max_length=200)),
                ('profile_image', models.ImageField(upload_to='images/profile_images/')),
                ('degree_image', models.ImageField(upload_to='images/degree_images/')),
                ('cnic_image', models.ImageField(upload_to='images/cnic_images/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('Country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Utility.country')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Utility.city')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Profile.profile')),
                ('subject', models.CharField(default='', max_length=500)),
                ('institute', models.CharField(default='', max_length=1000)),
                ('teaching_method', models.CharField(default='', max_length=1000)),
                ('study_days', models.CharField(default='', max_length=1000)),
                ('study_timing', models.CharField(default='', max_length=1000)),
            ],
            bases=('Profile.profile',),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Profile.profile')),
            ],
            bases=('Profile.profile',),
        ),
    ]
