# Generated by Django 3.2.4 on 2021-12-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20211223_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='study_days',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='prefered_teacher',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, null=True),
        ),
    ]
