# Generated by Django 4.0.5 on 2022-08-21 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0004_auto_20211223_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQualification',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('degree', models.CharField(default='', max_length=500)),
                ('subject', models.CharField(default='', max_length=500)),
                ('passing_year', models.CharField(default='', max_length=500)),
                ('institute', models.CharField(default='', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_qualifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
