# Generated by Django 4.0.5 on 2022-08-21 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0005_userqualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('position', models.CharField(default='', max_length=500)),
                ('from_data', models.CharField(default='', max_length=500)),
                ('to_data', models.CharField(default='', max_length=500)),
                ('institute', models.CharField(default='', max_length=500)),
                ('exprience_years', models.CharField(default='', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expriences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
