# Generated by Django 4.0.5 on 2022-08-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_profile_brith_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
