# Generated by Django 4.0.5 on 2022-08-21 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Utility', '0003_state_city_state'),
        ('Profile', '0008_profile_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Utility.state'),
        ),
    ]
