# Generated by Django 4.0.5 on 2022-08-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_profile_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexperience',
            old_name='from_data',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='userexperience',
            old_name='to_data',
            new_name='to_date',
        ),
    ]
