# Generated by Django 4.0.5 on 2022-08-21 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0010_rename_from_data_userexperience_from_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReferences',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=500)),
                ('mobile_number', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=500)),
                ('relation', models.CharField(default='', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_references', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
