# Generated by Django 4.0.5 on 2022-08-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_usermedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
