# Generated by Django 4.0.5 on 2022-08-24 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0013_remove_qualification_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfessionalDetail',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time_availability', models.CharField(default='', max_length=500)),
                ('areas_to_teach', models.CharField(default='', max_length=500)),
                ('online_teaching', models.CharField(default='', max_length=500)),
                ('home_tutor_status', models.CharField(default='', max_length=500)),
                ('own_institute', models.CharField(default='', max_length=500)),
                ('fee', models.CharField(default='', max_length=500)),
                ('currently_employeed', models.CharField(default='', max_length=500)),
                ('short_courses', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_professional_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
