# Generated by Django 4.0.5 on 2022-08-24 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0014_tutorprofessionaldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_languages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preferreddays',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_pref_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjecttoteach',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_subjects_to_teach', to=settings.AUTH_USER_MODEL),
        ),
    ]
