# Generated by Django 4.0.5 on 2022-08-24 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0015_language_user_preferreddays_user_subjecttoteach_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferreddays',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_preferred_days', to='Profile.profile'),
        ),
        migrations.AlterField(
            model_name='subjecttoteach',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subjects', to='Profile.teacherprofile'),
        ),
    ]
