# Generated by Django 4.0.5 on 2022-10-09 11:40

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
