# Generated by Django 4.0.5 on 2022-08-03 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VideoChat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videochat',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='VideoChatSetting',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('lock_meeting', models.BooleanField(default=False)),
                ('waiting_room', models.BooleanField(default=True)),
                ('share_screen', models.BooleanField(default=False)),
                ('allow_chat', models.BooleanField(default=False)),
                ('unmute', models.BooleanField(default=False)),
                ('start_video', models.BooleanField(default=False)),
                ('allow_rename', models.BooleanField(default=False)),
                ('muted_participant', models.ManyToManyField(related_name='muted_participants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_vchat_settings', to=settings.AUTH_USER_MODEL)),
                ('video_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_chat_settings', to='VideoChat.videochat')),
            ],
        ),
    ]
