# Generated by Django 4.0.5 on 2023-09-10 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VideoChat', '0002_alter_videochat_description_videochatsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoCallRequest',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_demo_classes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_demo_classes', to=settings.AUTH_USER_MODEL)),
                ('video_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videoroom_demo_classes', to='VideoChat.videochat')),
            ],
        ),
    ]
