# Generated by Django 4.0.5 on 2023-09-10 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VideoChat', '0003_democallrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoClassTimeSlot',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('selected_date', models.DateField()),
                ('selected_time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_timeslots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
