# Generated by Django 4.0.5 on 2023-09-10 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VideoChat', '0004_democlasstimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='democlasstimeslot',
            name='demo_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_timeslots', to='VideoChat.democallrequest'),
        ),
    ]
