# Generated by Django 4.0.5 on 2024-07-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoChat', '0005_democlasstimeslot_demo_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='videochat',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videochat',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videochat',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
