# Generated by Django 4.0.5 on 2024-07-02 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VideoChat', '0006_videochat_date_videochat_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videochat',
            name='paticipants',
            field=models.ManyToManyField(blank=True, related_name='participated_video_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
