# Generated by Django 4.0.5 on 2024-12-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoChat', '0009_democallrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='democallrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Requested', max_length=30),
        ),
    ]
