# Generated by Django 4.0.5 on 2024-12-11 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=999)),
                ('description', models.TextField()),
                ('class_teach', models.CharField(default='', max_length=999)),
                ('subject_teach', models.CharField(default='', max_length=999)),
                ('method', models.CharField(default='', max_length=999)),
                ('location', models.CharField(default='', max_length=999)),
                ('experience', models.CharField(default='', max_length=999)),
                ('salary', models.CharField(default='', max_length=999)),
                ('gender', models.CharField(default='', max_length=999)),
                ('time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=999)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_days', to='Job.job')),
            ],
        ),
    ]
