# Generated by Django 4.0.5 on 2024-12-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_applyjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
